### ISSUE TITLE
QR code valign

### ISSUE THREAD

**Issue by SukkoPera** [hpingel/sktp-server#1] opened 2024-07-23 22:08 UTC
https://github.com/hpingel/sktp-server/blob/6d097656d98603278eb583880f65f4baebf1bbf3/lib/puiQRCode.php#L133

I think this should be "top"/"bottom", or something similar :).

Also:
https://github.com/hpingel/sktp-server/blob/6d097656d98603278eb583880f65f4baebf1bbf3/lib/puiQRCode.php#L129

This does not work. I'm not a PHP expert but maybe two = are sufficient?

**Comment by hpingel** [comment] 2024-07-23 23:11
The comparison with === as such is fine, the parameter passed into the function can be either integer or string. This checks if the parameter is of type integer. It works as intended - but it could be shortened by using is_int().

**Comment by hpingel** [comment] 2024-07-23 23:16
fixed with https://github.com/hpingel/sktp-server/commit/18da0be04083c96c78c1507b84d22e44413eb8d0

**Closed as completed by hpingel** 2024-07-23 23:16 UTC
